### ISSUE TITLE
Bug: 14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by grunch** [jamaljsr/polar#286]
**Describe the bug**
Polar was working fine on my computer but suddenly it stop working, lnd nodes (alice, bob and charlie) changed status to error, when I select one and click the information tab I get

`14 UNAVAILABLE: failed to connect to all addresses`

**Desktop:**
- OS: Ubuntu 18.04.3 LTS
- Polar Version: 0.2.1
- Docker Version: 17.09.0 ce
- Docker Compose Version: 1.16.1

When I execute `docker logs` to one of the nodes I get this
```
goroutine 90 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc000430280)
	github.com/btcsuite/btcwallet@v0.11.0/wallet/chainntfns.go:117 +0x13fb
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
	github.com/btcsuite/btcwallet@v0.11.0/wallet/wallet.go:191 +0x1cb
Running as lnd user: lnd --noseedbackup --trickledelay=5000 --alias=bob --externalip=bob --tlsextradomain=bob --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser --bitcoind.rpcpass=polarpass --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334 --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
2020-01-27 15:41:37.990 [WRN] LTND: open /home/lnd/.lnd/lnd.conf: no such file or directory
2020-01-27 15:41:37.990 [INF] LTND: Version: 0.9.0-beta commit=v0.9.0-beta, build=production, logging=default
2020-01-27 15:41:37.990 [INF] LTND: Active chain: Bitcoin (network=regtest)
2020-01-27 15:41:37.991 [INF] CHDB: Checking for schema update: latest_version=12, db_version=12
2020-01-27 15:41:38.058 [INF] LTND: Primary chain is set to: bitcoin
2020-01-27 15:41:38.062 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 172.19.0.4:28334
2020-01-27 15:41:38.062 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 172.19.0.4:28335
2020-01-27 15:41:39.065 [INF] LNWL: Opened wallet
2020-01-27 15:41:39.777 [INF] LNWL: The wallet has been unlocked without a time limit
2020-01-27 15:41:39.787 [INF] LTND: LightningWallet opened
panic: Unable to synchronize wallet to chain: -8: Block height out of range

goroutine 84 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc00047c140)
	github.com/btcsuite/btcwallet@v0.11.0/wallet/chainntfns.go:117 +0x13fb
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
	github.com/btcsuite/btcwallet@v0.11.0/wallet/wallet.go:191 +0x1cb
Running as lnd user: lnd --noseedbackup --trickledelay=5000 --alias=bob --externalip=bob --tlsextradomain=bob --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser --bitcoind.rpcpass=polarpass --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334 --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
2020-01-27 15:42:40.880 [WRN] LTND: open /home/lnd/.lnd/lnd.conf: no such file or directory
2020-01-27 15:42:40.881 [INF] LTND: Version: 0.9.0-beta commit=v0.9.0-beta, build=production, logging=default
2020-01-27 15:42:40.881 [INF] LTND: Active chain: Bitcoin (network=regtest)
2020-01-27 15:42:40.884 [INF] CHDB: Checking for schema update: latest_version=12, db_version=12
2020-01-27 15:42:40.953 [INF] LTND: Primary chain is set to: bitcoin
2020-01-27 15:42:40.958 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 172.19.0.4:28334
2020-01-27 15:42:40.958 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 172.19.0.4:28335
2020-01-27 15:42:41.959 [INF] LNWL: Opened wallet
2020-01-27 15:42:42.695 [INF] LNWL: The wallet has been unlocked without a time limit
2020-01-27 15:42:42.700 [INF] LTND: LightningWallet opened
panic: Unable to synchronize wallet to chain: -8: Block height out of range

goroutine 44 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc000474780)
	github.com/btcsuite/btcwallet@v0.11.0/wallet/chainntfns.go:117 +0x13fb
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
	github.com/btcsuite/btcwallet@v0.11.0/wallet/wallet.go:191 +0x1cb
```

**Comment by jamaljsr** [comment]
This is an error I have not seen before. I did a quick search through the LND repo code/issues for this error but didn't come up with any solutions. I also skimmed through the [btcwallet](https://github.com/btcsuite/btcwallet/blob/704cd189ac2386b54ab64e17f67f1c7c5ef5c7ac/wallet/chainntfns.go#L117) code where that error originates. It looks to me that somehow your bitcoind is currently on a block height lower than when the LND wallet was created, which should not be possible. My guess is that somehow your bitcoin or lnd data got corrupted. 

To solve the issue, you could try asking some of the LND folks on github or slack if it is possible to recover from this situation, or you can take the easy way out and just create a new network. This is one of the benefits of Polar, making these local regtest networks easily disposable. If you manage to break it, you can just start a new one in a few clicks.

**Comment by grunch** [comment]
Yeah, deleled the network and created a new one, just wanna to let you know about the issue, maybe it can happen to other of your users, I'll close this issue.

**Comment by bolatovumar** [comment]
I'm also getting this issue fairly consistently. Deleting the network and creating a new one helps but not always. Sometimes the new network gives you the same error right away. It's not a big deal but just thought I would mention it.

**Comment by jamaljsr** [comment]
@bolatovumar I wonder if this is caused by the new LND v0.9.0 release.

Were you receiving the same error message in the docker logs?
'panic: Unable to synchronize wallet to chain: -8: Block height out of range'

Are you running on Ubuntu as well?

If this happens again, would you mind sharing your `~/.polar/networks` dir with me.

**Comment by bolatovumar** [comment]
@jamaljsr i deleted those networks manually from the `~/.polar/networks` folder. I'm running macOS Mojave. Also, I was using LND 0.8.2. I have this screenshot of the error message in dev:

![Screen Shot 2020-02-04 at 6 50 01 PM](https://user-images.githubusercontent.com/1934678/73871631-08534c80-4803-11ea-9356-05e0f866c811.png)

I could take a look at Docker logs but not sure how to get to them.

**Comment by jamaljsr** [comment]
ok, if you see it again and would like to troubleshoot, you can run `docker-compose logs alice` from within the dir containing the docker-compose.yml file for the network.

**Comment by bolatovumar** [comment]
@jamaljsr will do
