### ISSUE TITLE
Bug: Permission denied './docker-compose.yml' when trying to start the network / a node

### ISSUE THREAD

**Issue by cstenglein** [jamaljsr/polar#447]
**Describe the bug**
When trying to start a newly created network, the error message:

`.PermissionError: [Errno 13] Permission denied: './docker-compose.yml'`

This happens for both trying to start a single node as well as starting the whole network via the orange start button.

Downloading the docker images by hand didn't change the behaviour.

EDIT: This makes it also unable to delete a network.

**To Reproduce**
1. Go to a network
2. Click on the orange start button.
3. See error

**Expected behavior**
Starting the network without failure.

**Screenshots**

![image](https://user-images.githubusercontent.com/9399034/114372952-a3ffeb80-9b71-11eb-928b-71804150ef63.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 20.10
- Polar Version: 1.2.0
- Docker Version: 19.03.13
- Docker Compose Version: 1.25.5

**Log**

```
[2021-04-12 11:31:01.239] [warn] Unable to start the node Error: .PermissionError: [Errno 13] Permission denied: './docker-compose.yml'

    at file:///tmp/.mount_polar-wnOEyz/resources/app.asar/build/static/js/main.388656e4.chunk.js:1:233527
    at u (file:///tmp/.mount_polar-wnOEyz/resources/app.asar/build/static/js/2.c754c03b.chunk.js:2:424011)
    at Generator._invoke (file:///tmp/.mount_polar-wnOEyz/resources/app.asar/build/static/js/2.c754c03b.chunk.js:2:423799)
    at Generator.S.forEach.e.<computed> [as throw] (file:///tmp/.mount_polar-wnOEyz/resources/app.asar/build/static/js/2.c754c03b.chunk.js:2:424434)
    at r (file:///tmp/.mount_polar-wnOEyz/resources/app.asar/build/static/js/2.c754c03b.chunk.js:2:1131)
    at c (file:///tmp/.mount_polar-wnOEyz/resources/app.asar/build/static/js/2.c754c03b.chunk.js:2:1370)
```
EDIT: added log

**Comment by cstenglein** [comment]
Solution:

I had docker installed as a `snap` package. This doesn't seem to work since polar doesn't seem to be in the `docker` group (see [snapcraft link to docker](https://snapcraft.io/docker).

Uninstalling the snap package with `snap remove docker --purge` and installing docker + docker compose with the [install instructions](https://docs.docker.com/engine/install/ubuntu/) worked.
