### ISSUE TITLE
Bug: Cannot find module '@hodlone/tapd-api'

### ISSUE THREAD

**Issue by johnnyasantoss** [jamaljsr/polar#717]
**Describe the bug**
Error when launching the AppImage with version `2.0.0-rc2`.

**To Reproduce**
1. Download the appimage
2. Run it on a terminal
3. See error

**Expected behavior**
Open

**Screenshots**

The log:
```stacktrace
./polar-linux-x86_64-v2.0.0-rc2_6f20d3832802cfe1725a97a43aa257c2.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@hodlone/tapd-api'
Require stack:
- /tmp/.mount_polar-AdrE1F/resources/app.asar/build/main/electron/tapd/tapdProxyServer.js
- /tmp/.mount_polar-AdrE1F/resources/app.asar/build/main/electron/appIpcListener.js
- /tmp/.mount_polar-AdrE1F/resources/app.asar/build/main/electron/windowManager.js
- /tmp/.mount_polar-AdrE1F/resources/app.asar/build/main/electron/index.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_polar-AdrE1F/resources/app.asar/build/main/electron/tapd/tapdProxyServer.js:29:27)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
```

**Desktop (please complete the following information):**
- OS: 
```
System:
  Kernel: 5.15.109-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 12.2.1
    Desktop: GNOME v: 43.5 Distro: Manjaro Linux base: Arch Linux
```
- Polar Version: `2.0.0-rc2`
- Docker Version: `Docker version 23.0.4, build f480fb1e37`
- Docker Compose Version: `Docker Compose version 2.17.3`

**Additional context**

**Comment by jamaljsr** [comment]
Thanks for the report, the rc2 binaries got screwed up. I just released [v2.0.0-rc3](https://github.com/jamaljsr/polar/releases/tag/v2.0.0-rc3) to resolve this issue.
