### ISSUE TITLE
Bug: python3 list.py can not connect to alice-tapd

### ISSUE THREAD

**Issue by xiaoyu1998** [jamaljsr/polar#821]
**Describe the bug**
python3 list.py can not connect to alice-tapd

**Desktop**
- OS: maxOS Monterey 12.2.1
- Polar Version: 2.1.0
- Docker Version: 20.10.22
- Docker Compose Version: v2.15.1

**Comment by xiaoyu1998** [comment]
(base) xiaoyu@192 tapd-python-scripts % python3 list.py
Traceback (most recent call last):
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/xiaoyu/anaconda3/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff563d9c5e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //127.0.0.1:8289/v1/taproot-assets/assets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff563d9c5e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xiaoyu/work/nostr/tapd-python-scripts/list.py", line 23, in <module>
    main()
  File "/Users/xiaoyu/work/nostr/tapd-python-scripts/list.py", line 13, in main
    response = requests.get(url, headers=headers, verify=TLS_PATH)
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/xiaoyu/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //127.0.0.1:8289/v1/taproot-assets/assets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff563d9c5e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

**Comment by jamaljsr** [comment]
Hey @xiaoyu1998, This doesn't seem like an issue with Polar. The error `[Errno 8] nodename nor servname provided, or not known` implies that you aren't providing a hostname to whatever function you are calling. Have you tried testing with the sample code provided in the `tapd` [API docs](https://lightning.engineering/api-docs/api/taproot-assets/taproot-assets/list-assets)?

**Comment by xiaoyu1998** [comment]
i am running this code
https://github.com/HannahMR/tapd-python-scripts

**Comment by xiaoyu1998** [comment]
thanks it can work now
